[build]
  base    = "angularapp-frontend"
  command = "npm run build"
  publish = "dist/angularapp"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"